service: node-trader
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  endpointType: regional

functions:
  execute-trade:
    handler: handlers/trade-handler.execute
    events:
      - http:
          path: trade/actions/execute
          method: post
    environment:
      use_sandbox: ${file(./config/config.js):fetchUseSandbox}
      coinbase_api_key: ${file(./config/config.js):fetchCoinbaseApiKey}
      coinbase_api_secret: ${file(./config/config.js):fetchCoinbaseApiSecret}
      coinbase_api_passphrase: ${file(./config/config.js):fetchCoinbaseApiPassphrase}
      mongodb_url: ${file(./config/config.js):fetchMongodbUrl}

  fetch-trades:
    handler: handlers/trade-handler.all
    events:
      - http:
          path: trade
          method: get
    environment:
      use_sandbox: ${file(./config/config.js):fetchUseSandbox}
      coinbase_api_key: ${file(./config/config.js):fetchCoinbaseApiKey}
      coinbase_api_secret: ${file(./config/config.js):fetchCoinbaseApiSecret}
      coinbase_api_passphrase: ${file(./config/config.js):fetchCoinbaseApiPassphrase}
      mongodb_url: ${file(./config/config.js):fetchMongodbUrl}

  summary:
    handler: handlers/summary-handler.generate
    events:
      - http:
          path: summary
          method: get
    environment:
      use_sandbox: ${file(./config/config.js):fetchUseSandbox}
      coinbase_api_key: ${file(./config/config.js):fetchCoinbaseApiKey}
      coinbase_api_secret: ${file(./config/config.js):fetchCoinbaseApiSecret}
      coinbase_api_passphrase: ${file(./config/config.js):fetchCoinbaseApiPassphrase}
      mongodb_url: ${file(./config/config.js):fetchMongodbUrl}

plugins:
  - serverless-offline
